version: '3'
services:
  user:
    build:
      context: ./Distributed_Server/User_Server
      dockerfile: ./Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongo

  post:
    build:
      context: ./Distributed_Server/Post_Server
      dockerfile: ./Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongo
      - minio

  notification:
    build:
      context: ./Distributed_Server/Notification_Server
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  minio:
    image: minio/minio:latest
    environment:
     - ./Distributed_Server/Post_Server/.env
    command: minio server /minIO 0.0.0.0:9000/linkedin

  mongo:
    image: mongo:latest
    # environment:
    #  - ./Distributed_Server/Post_Server/.env
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: