version: '3'
services:
  user:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongo
      - minio

    
  mongo:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - linkedin:/data/db

  minio:
    image: minio/minio:latest
    environment:
     - .env
    command: server --address 0.0.0.0:9000 /linkedin
  